export const FETCH_USER_DETAILS_START = "FETCH_USER_DETAILS_START";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";
export const FETCH_USER_POST_SUCCESS = "FETCH_USER_POST_SUCCESS";
export const FETCH_USER_TODO_SUCCESS = 'FETCH_USER_TODO_SUCCESS'
export const FETCH_USER_COMMENT_SUCCESS = 'FETCH_USER_COMMENT_SUCCESS'



